[kafkaTopology]
shutDownTimeout = "PT5S"
periodeTopic = "${KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC}"
microfrontendTopic = "${KAFKA_TMS_MICROFRONTEND_TOPIC}"
periodeStreamIdSuffix = "${KAFKA_ARBEIDSSOKERPERIODER_STREAM_ID_SUFFIX}"
toggleProducerIdSuffix = "${KAFKA_TOGGLE_PRODUCER_ID_SUFFIX}"
periodeStateStore = "microfrontendTogglePeriodeStore"

[microfrontendToggle]
periodeTogglePunctuatorSchedule = "PT6H"
utsattDeaktiveringAvAiaMinSide = "P21D"
