beholdAlleStillingerPublisertEtter = "2024-01-01T00:00:00+01:00"
beholdIkkeAktiveStillingerMedUtloeperNyereEnn = "P90D"

[pamStillingerKafkaConsumer]
version = 2
topic = "teampam.stilling-ekstern-1"
groupIdPrefix = "paw-arbeidssoekerregisteret-api-ledigestillinger-stilling-ekstern"

[databaseMetricsScheduledTask]
name = "DatabaseMetrics"
delay = "PT1M"
period = "PT10M"

[databaseCleanupScheduledTask]
name = "DatabaseCleanup"
delay = "PT5M"
period = "PT1H"