[kafkaTopology]
shutDownTimeout = "PT1S"
periodeTopic = "paw.arbeidssokerperioder-v1"
microfrontendTopic = "min-side.aapen-microfrontend-v1"
periodeStreamIdSuffix = "arbeidssokerperioder-stream-v1"
toggleProducerIdSuffix = "toggle-producer-v1"
periodeStateStore = "microfrontendTogglePeriodeStore"

[microfrontendToggle]
periodeTogglePunctuatorSchedule = "PT5M"
utsattDeaktiveringAvAiaMinSide = "PT15M"
