[[authProviders]]
name = "azure"
audiences = ["paw-arbeidssoekerregisteret-api-oppslag-v2"]
discoveryUrl = "http://localhost:8081/azure/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["NAVident"]
