[[authProviders]]
name = "azure"
audiences = ["egenvurdering-dialog-tjeneste"]
discoveryUrl = "http://localhost:8081/azure/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["NAVident"]
